name: DGUI
version: '1.0-SNAPSHOT'
main: myplugins.docks.Dgui.DGUI
api-version: '1.20'
commands:
  agui:
    description: Open the command GUI.
    usage: /agui
    permission: Docks.use
    permission-message: "&cYou do not have permission to use this command."